<a href="https://colab.research.google.com/github/Fezzaioussama/Reinforcement-Learning/blob/main/Reinforcement_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Value iteration

In [1]:
!pip install gym

In [89]:
import gym
import numpy as np

env = gym.make('FrozenLake-v1')
num_states = env.observation_space.n
num_actions = env.action_space.n
max_iterations = 1000
delta = 10**-3

epsilon =0.9

gamma = 0.9

R = np.zeros([num_states, num_actions, num_states])
T = np.zeros([num_states, num_actions, num_states])
V = np.zeros([env.observation_space.n])
Q = np.zeros([env.observation_space.n, env.action_space.n])


print("FrozenLake-v1")
print("Actions: ", num_actions)
print("States: ", num_states)
print(env.env.desc)

FrozenLake-v1
Actions:  4
States:  16
[[b'S' b'F' b'F' b'F']
 [b'F' b'H' b'F' b'H']
 [b'F' b'F' b'F' b'H']
 [b'H' b'F' b'F' b'G']]


/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [90]:
precedant_value=np.zeros([env.observation_space.n])
polisy=np.zeros([env.observation_space.n])
v=0
discount=0.9
count=0

for i in range(100000):
  precedant_value=np.copy(V)
  for s in range(env.observation_space.n):

    Q=[]
    for a in range(env.action_space.n):
      q=[]
      for transition in env.env.P[s][a]:

          prop,ns,reward,done=transition

          R[s,a,ns]=reward
          T[s,a,ns]=prop
          q.append(prop*(reward+discount*V[ns]))
      Q.append(np.sum(q))

    polisy[s]=np.argmax(Q)
    V[s]=np.max(Q)


  if (np.sum(np.fabs(V - precedant_value)))<1e-20:
    print ('Value-iteration converged at iteration# %d.' %(i+1))
    break

Value-iteration converged at iteration# 196.


In [92]:
print(polisy)

[0. 3. 0. 3. 0. 0. 0. 0. 3. 1. 0. 0. 0. 2. 1. 0.]


#SARSA

In [145]:
import gym
import numpy as np

env = gym.make('FrozenLake-v1')
num_states = env.observation_space.n
num_actions = env.action_space.n
max_iterations = 1000
delta = 10**-3

epsilon =0.9

gamma = 0.9

R = np.zeros([num_states, num_actions, num_states])
T = np.zeros([num_states, num_actions, num_states])
V = np.zeros([env.observation_space.n])
Q = np.zeros([env.observation_space.n, env.action_space.n])


print("FrozenLake-v1")
print("Actions: ", num_actions)
print("States: ", num_states)
print(env.env.desc)

FrozenLake-v1
Actions:  4
States:  16
[[b'S' b'F' b'F' b'F']
 [b'F' b'H' b'F' b'H']
 [b'F' b'F' b'F' b'H']
 [b'H' b'F' b'F' b'G']]


In [140]:
import random
def epsilon_greedy(state, epsilon):
    if random.uniform(0,1) < epsilon:
        return env.action_space.sample()
    else:
        return max(list(range(env.action_space.n)), key = lambda x: Q[(state,x)])

In [141]:
precedant_value=np.zeros([env.observation_space.n])
polisy=np.zeros([env.observation_space.n])
discount=0.9
alpha=0.85

In [142]:
for i in range(4000):
  precedant_value=np.copy(V)
  s=env.reset()
  a=epsilon_greedy(s, 0.8)
  while True:
    ns, reward, done, _ = env.step(a)

    na = epsilon_greedy(ns,epsilon)
    Q[s,a]=(1-alpha)*Q[s,a]+(reward+discount*Q[ns,na])

    s=ns
    a=na
    if done:
      break
  for s in range(env.observation_space.n):
    V[s]=np.max(Q[s,:])
    polisy[s]=np.argmax(Q[s,:])
  # if (np.sum(np.fabs(V - precedant_value)))<1e-20:
  #   print ('Value-iteration converged at iteration# %d.' %(i+1))
  #   break

In [143]:
print(Q)

[[3.44423032e-02 3.04901161e-02 2.83660829e-02 8.99308968e-03]
 [6.75397883e-03 5.75140537e-04 3.22448402e-03 7.67680172e-02]
 [5.03930392e-02 2.49609465e-03 1.14120704e-01 1.81739539e-02]
 [9.75668406e-02 7.25215906e-02 1.58156962e-02 1.87430929e-03]
 [1.31250289e-01 2.17972889e-02 8.57522787e-02 2.26292829e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.03493145e+00 8.51576111e-11 6.08528300e-03 2.13312892e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.37723625e-02 9.53593189e-02 6.77732713e-02 2.59279702e-02]
 [3.38603387e-02 3.27533372e-01 3.95966874e-01 9.47329474e-03]
 [2.84350626e-01 9.96761873e-02 3.94251778e-03 1.12860875e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.51889187e-01 3.05265281e-03 7.63262506e-01 7.17480278e-02]
 [3.05115242e-01 1.06031402e+00 1.68429089e-01 9.36204604e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [144]:
print(polisy)
print(V)

[0. 3. 2. 0. 0. 0. 0. 0. 1. 2. 0. 0. 0. 2. 1. 0.]
[0.0344423  0.07676802 0.1141207  0.09756684 0.13125029 0.
 1.03493145 0.         0.09535932 0.39596687 0.28435063 0.
 0.         0.76326251 1.06031402 0.        ]


#Q learning

In [151]:
import gym
import numpy as np

env = gym.make('FrozenLake-v1')
num_states = env.observation_space.n
num_actions = env.action_space.n
max_iterations = 1000
delta = 10**-3

epsilon =0.9

gamma = 0.9

R = np.zeros([num_states, num_actions, num_states])
T = np.zeros([num_states, num_actions, num_states])
V = np.zeros([env.observation_space.n])
Q = np.zeros([env.observation_space.n, env.action_space.n])


print("FrozenLake-v1")
print("Actions: ", num_actions)
print("States: ", num_states)
print(env.env.desc)

FrozenLake-v1
Actions:  4
States:  16
[[b'S' b'F' b'F' b'F']
 [b'F' b'H' b'F' b'H']
 [b'F' b'F' b'F' b'H']
 [b'H' b'F' b'F' b'G']]


/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [161]:
R = np.zeros([num_states, num_actions, num_states])
T = np.zeros([num_states, num_actions, num_states])
V = np.zeros([env.observation_space.n])
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [162]:
import random
def epsilon_greedy(state, epsilon):
    if random.uniform(0,1) < epsilon:
        return env.action_space.sample()
    else:
        return max(list(range(env.action_space.n)), key = lambda x: Q[(state,x)])

In [163]:
precedant_value=np.zeros([env.observation_space.n])
polisy=np.zeros([env.observation_space.n])
discount=0.9
alpha=0.85

In [164]:
for i in range(4000):
  precedant_value=np.copy(V)
  s=env.reset()
  a=epsilon_greedy(s, 0.8)

  while True:
    a=epsilon_greedy(s, 0.8)
    ns, reward, done, _ = env.step(a)
    Q[s,a]=(1-alpha)*Q[s,a]+(reward+discount*(np.max(Q[ns,:])))
    s=ns

    if done:
      break

  for s in range(env.observation_space.n):
    V[s]=np.max(Q[s,:])
    polisy[s]=np.argmax(Q[s,:])

  # if (np.sum(np.fabs(V - precedant_value)))<1e-20:
  #   print ('Value-iteration converged at iteration# %d.' %(i+1))
  #   break

In [165]:
print(Q)
print(V)
print(polisy)

[[1.02508663e+88 1.23404262e+88 7.16062661e+87 1.15936903e+88]
 [7.46405381e+87 2.44359963e+87 4.65960391e+86 3.02248579e+87]
 [8.17193145e+86 1.35596681e+86 1.34094513e+87 9.56355150e+86]
 [1.74676593e+86 8.46985757e+86 7.36182207e+84 7.63494111e+86]
 [6.21295691e+87 2.63206194e+87 9.38556517e+87 6.43761007e+87]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.02362182e+86 2.18958102e+83 8.97469731e+76 1.22575652e+87]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.77793549e+87 6.50251633e+85 7.85323836e+86 2.74456651e+87]
 [5.46882018e+83 3.75929955e+86 1.67868342e+84 5.52591549e+84]
 [1.62191185e+84 1.31582925e+78 1.57728727e+83 1.30451533e+86]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.63235208e+84 1.84016652e+83 4.03083521e+84 2.36593277e+82]
 [1.75254140e+83 1.75252686e+83 1.92114309e+75 4.54069800e+78]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000